### PR TITLE
Lookup prefixes dynamically

### PR DESCRIPTION
**Pull request by cbizon**
Addresses https://github.com/ranking-agent/aragorn-ranker/issues/12

One thing that appears to be happening is that we don't keep the paper counts for nodes in the cache, so those always go to postgres (should update this too)

The postgres omnicorp checked the prefixes against an internal list, but that list needs to be updated regularly.  This version checks postgres and just pulls what tables are there, rather than hard coding it.

It also handles that some prefixes have "." in them, which have to be converted to "_" as a table name.

This hasn't been fully tested, can you take a look @PhillipsOwen ?

### CODE REVIEW

**Review by PhillipsOwen — COMMENTED** [review]
I loaded the code locally and verified that the prod connections to postgres and redis were were returning data (pmid counts) using famcov_new.json.

i note that NCBITaxon, NCBIGene curies are not getting handled (not in self.prefixes).

I will look into the tests now.

**Comment by cbizon** [comment]
> i note that NCBITaxon, NCBIGene curies are not getting handled (not in self.prefixes).

You mean in master?  Or on the PR?  Fixing this was the main goal of the PR (it also wouldn't handle pubchem.compound among others)

**Comment by PhillipsOwen** [comment]
sorry let me test this again. i didnt pull the branch properly

**Comment by PhillipsOwen** [comment]
prefix = curie.lower().split(':')
 prefix = '_'.join(prefix.split('.')) is throwing -> AttributeError: 'list' object has no attribute 'split'
 
 did you mean:
 prefix = '_'.join(prefix[0].split('.'))

**Comment by cbizon** [comment]
> did you mean:
> prefix = '_'.join(prefix[0].split('.'))

Oops, yeah.  Thanks

**Review by PhillipsOwen — APPROVED** [review]

**Pull request merged**
