### PR TITLE
Trapi15

### PR DESCRIPTION
**Pull request by cbizon**
I don't know if this is going to have any trouble with Abrar's changes, but the tests should now be active again.

### CODE REVIEW

**Comment by cbizon** [comment]
It looks like the failing tests are omnicorp related & not TRAPI related.  I'll take a closer look though.

**Comment by cbizon** [comment]
OK, tests restored.

**Review by maximusunc — APPROVED** [review]
There shouldn't be too much overlap with Abrar's PR, and it's probably a good thing to fix the tests before we get the other PR merged anyways.

**Comment by cbizon** [comment]
OK, I modified the cache as discussed this morning.  The one tricky thing is that overwrite_cache defaults to False so I think we lose e.g. caching of CQS queries.

I also added logs:[] to created Responses (which happens when we make an infer response at merge time)

**Pull request merged**
